/* =============================================
   LearnHub - Mock Data
   ============================================= */

const MOCK = {

  /* ─── CATEGORIES ─── */
  categories: [
    { id: 1, name: 'Web Development',   icon: '💻', courses: 1240, color: 'purple' },
    { id: 2, name: 'Data Science',      icon: '📊', courses: 876,  color: 'mint' },
    { id: 3, name: 'UI/UX Design',      icon: '🎨', courses: 543,  color: 'warm' },
    { id: 4, name: 'Mobile Apps',       icon: '📱', courses: 432,  color: 'purple' },
    { id: 5, name: 'Business',          icon: '💼', courses: 612,  color: 'mint' },
    { id: 6, name: 'Digital Marketing', icon: '📣', courses: 387,  color: 'warm' },
    { id: 7, name: 'Photography',       icon: '📷', courses: 298,  color: 'purple' },
    { id: 8, name: 'Music',             icon: '🎵', courses: 234,  color: 'mint' },
  ],

  /* ─── INSTRUCTORS ─── */
  instructors: [
    {
      id: 1, name: 'Sarah Johnson',
      avatar: 'https://ui-avatars.com/api/?name=Sarah+Johnson&background=CA895F&color=fff&size=128',
      title: 'Senior Full-Stack Developer',
      rating: 4.9, students: 45200, courses: 8,
      bio: 'Full-stack developer with 12+ years building scalable web applications. Previously at Google and Shopify.',
    },
    {
      id: 2, name: 'Mark Chen',
      avatar: 'https://ui-avatars.com/api/?name=Mark+Chen&background=A49BF0&color=fff&size=128',
      title: 'Data Science Lead at TechCorp',
      rating: 4.8, students: 32100, courses: 5,
      bio: 'Data scientist and ML engineer passionate about making data science accessible to everyone.',
    },
    {
      id: 3, name: 'Priya Patel',
      avatar: 'https://ui-avatars.com/api/?name=Priya+Patel&background=A8E8B5&color=595758&size=128',
      title: 'Lead Product Designer',
      rating: 4.9, students: 28700, courses: 6,
      bio: 'Award-winning UX designer with expertise in creating intuitive digital experiences for Fortune 500 companies.',
    },
    {
      id: 4, name: 'Alex Rivera',
      avatar: 'https://ui-avatars.com/api/?name=Alex+Rivera&background=EBD2B4&color=595758&size=128',
      title: 'iOS & Android Engineer',
      rating: 4.7, students: 19400, courses: 4,
      bio: 'Mobile developer with 8 years building apps with 10M+ downloads on both iOS and Android platforms.',
    },
    {
      id: 5, name: 'Lisa Wong',
      avatar: 'https://ui-avatars.com/api/?name=Lisa+Wong&background=CA895F&color=fff&size=128',
      title: 'Digital Marketing Strategist',
      rating: 4.8, students: 22900, courses: 7,
      bio: 'Digital marketing expert who has generated $50M+ in revenue for e-commerce brands through data-driven campaigns.',
    },
  ],

  /* ─── COURSES ─── */
  courses: [
    {
      id: 1,
      title: 'Complete Web Development Bootcamp 2024',
      slug: 'complete-web-development-bootcamp',
      instructorId: 1,
      instructor: 'Sarah Johnson',
      category: 'Web Development',
      level: 'Beginner',
      rating: 4.8, reviews: 12430, students: 89000,
      price: 1990, originalPrice: 3990,
      duration: '52h 30m', lessons: 289, sections: 18,
      thumbnail: 'https://picsum.photos/seed/web1/640/360',
      isBestseller: true, isNew: false,
      tags: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
      language: 'ไทย/English',
      lastUpdated: 'พฤศจิกายน 2024',
      description: 'หลักสูตรพัฒนาเว็บแบบครบวงจร เรียนรู้ HTML, CSS, JavaScript, React และ Node.js จากพื้นฐานถึงระดับมืออาชีพ',
      whatYouLearn: [
        'สร้างเว็บไซต์ด้วย HTML5 และ CSS3 อย่างมืออาชีพ',
        'เขียน JavaScript ทั้ง ES6+ modern syntax',
        'พัฒนา React applications ด้วย hooks',
        'สร้าง REST API ด้วย Node.js และ Express',
        'ทำงานกับ Database ทั้ง SQL และ MongoDB',
        'Deploy แอปไปยัง Cloud (AWS/Vercel)',
        'Version control ด้วย Git และ GitHub',
        'Responsive design และ Mobile-first approach',
      ],
      curriculum: [
        { section: 'Introduction to Web Development', lessons: ['Welcome!', 'How the Web Works', 'Setting Up Your Environment', 'HTML Basics'], duration: '2h 15m' },
        { section: 'HTML5 Deep Dive', lessons: ['Semantic HTML', 'Forms & Validation', 'Multimedia', 'HTML Best Practices'], duration: '3h 40m' },
        { section: 'CSS Mastery', lessons: ['CSS Selectors', 'Box Model', 'Flexbox', 'Grid', 'Animations', 'Responsive Design'], duration: '5h 20m' },
        { section: 'JavaScript Fundamentals', lessons: ['Variables & Types', 'Functions', 'Arrays & Objects', 'DOM Manipulation', 'Events', 'Async JS'], duration: '8h 10m' },
        { section: 'React Framework', lessons: ['React Introduction', 'Components', 'State & Props', 'Hooks', 'Router', 'State Management'], duration: '10h 45m' },
        { section: 'Backend with Node.js', lessons: ['Node.js Setup', 'Express Framework', 'REST APIs', 'Authentication', 'Database Integration'], duration: '7h 30m' },
        { section: 'Full-Stack Projects', lessons: ['Blog App', 'E-commerce Platform', 'Real-time Chat', 'Portfolio Website'], duration: '14h 50m' },
      ],
    },
    {
      id: 2,
      title: 'Data Science & Machine Learning Masterclass',
      slug: 'data-science-ml-masterclass',
      instructorId: 2,
      instructor: 'Mark Chen',
      category: 'Data Science',
      level: 'Intermediate',
      rating: 4.9, reviews: 8750, students: 52000,
      price: 2490, originalPrice: 4990,
      duration: '65h 20m', lessons: 341, sections: 22,
      thumbnail: 'https://picsum.photos/seed/data2/640/360',
      isBestseller: true, isNew: false,
      tags: ['Python', 'Machine Learning', 'Deep Learning', 'TensorFlow', 'Pandas'],
      language: 'English',
      lastUpdated: 'ตุลาคม 2024',
      description: 'เรียนรู้ Data Science และ Machine Learning ตั้งแต่พื้นฐาน Python ไปจนถึง Deep Learning models',
      whatYouLearn: [
        'Python programming สำหรับ Data Science',
        'Data analysis ด้วย Pandas และ NumPy',
        'Data visualization ด้วย Matplotlib และ Seaborn',
        'Machine Learning algorithms หลัก',
        'Deep Learning ด้วย TensorFlow และ Keras',
        'Natural Language Processing (NLP)',
        'Computer Vision basics',
        'Model deployment',
      ],
      curriculum: [
        { section: 'Python for Data Science', lessons: ['Python Basics', 'NumPy', 'Pandas', 'Matplotlib'], duration: '8h 30m' },
        { section: 'Statistical Analysis', lessons: ['Descriptive Stats', 'Inferential Stats', 'Hypothesis Testing', 'A/B Testing'], duration: '5h 45m' },
        { section: 'Machine Learning', lessons: ['Linear Regression', 'Classification', 'Clustering', 'Ensemble Methods', 'Model Evaluation'], duration: '12h 20m' },
        { section: 'Deep Learning', lessons: ['Neural Networks', 'CNNs', 'RNNs', 'Transfer Learning', 'GANs'], duration: '14h 10m' },
        { section: 'Real Projects', lessons: ['Customer Churn', 'Image Classifier', 'NLP Sentiment', 'Stock Predictor'], duration: '24h 35m' },
      ],
    },
    {
      id: 3,
      title: 'UI/UX Design Professional Certificate',
      slug: 'ui-ux-design-professional',
      instructorId: 3,
      instructor: 'Priya Patel',
      category: 'UI/UX Design',
      level: 'Beginner',
      rating: 4.9, reviews: 6230, students: 38400,
      price: 1790, originalPrice: 3490,
      duration: '38h 15m', lessons: 198, sections: 14,
      thumbnail: 'https://picsum.photos/seed/design3/640/360',
      isBestseller: false, isNew: true,
      tags: ['Figma', 'Prototyping', 'User Research', 'Design Systems'],
      language: 'English',
      lastUpdated: 'ธันวาคม 2024',
      description: 'หลักสูตร UI/UX Design ครบวงจร เรียนรู้ Figma, Design Thinking และ User Research จากนักออกแบบระดับโลก',
      whatYouLearn: [
        'Design Thinking และ Human-Centered Design',
        'User Research และ Persona creation',
        'Wireframing และ Prototyping ด้วย Figma',
        'Design Systems และ Component libraries',
        'Usability Testing',
        'Accessibility ใน Design',
      ],
      curriculum: [
        { section: 'Design Foundations', lessons: ['Design Principles', 'Color Theory', 'Typography', 'Layout'], duration: '4h 30m' },
        { section: 'UX Research', lessons: ['User Interviews', 'Personas', 'User Journey Maps', 'Competitive Analysis'], duration: '6h 15m' },
        { section: 'Figma Mastery', lessons: ['Figma Interface', 'Components', 'Auto Layout', 'Prototyping', 'Variables'], duration: '10h 45m' },
        { section: 'Design Systems', lessons: ['Atomic Design', 'Component Library', 'Documentation'], duration: '5h 20m' },
        { section: 'Portfolio Projects', lessons: ['Mobile App Design', 'Web App Dashboard', 'Brand Identity'], duration: '11h 25m' },
      ],
    },
    {
      id: 4,
      title: 'iOS & Android App Development with Flutter',
      slug: 'flutter-mobile-development',
      instructorId: 4,
      instructor: 'Alex Rivera',
      category: 'Mobile Apps',
      level: 'Intermediate',
      rating: 4.7, reviews: 4120, students: 24500,
      price: 2190, originalPrice: 4290,
      duration: '44h 50m', lessons: 245, sections: 16,
      thumbnail: 'https://picsum.photos/seed/mobile4/640/360',
      isBestseller: false, isNew: false,
      tags: ['Flutter', 'Dart', 'Firebase', 'iOS', 'Android'],
      language: 'English',
      lastUpdated: 'กันยายน 2024',
      description: 'สร้าง iOS และ Android apps ด้วย Flutter และ Dart ภาษาเดียว 2 platforms',
      whatYouLearn: ['Dart programming', 'Flutter widgets', 'State management (Riverpod)', 'Firebase integration', 'App store deployment'],
      curriculum: [
        { section: 'Dart Fundamentals', lessons: ['Dart Basics', 'OOP in Dart', 'Async Programming'], duration: '5h 20m' },
        { section: 'Flutter Basics', lessons: ['Widgets', 'Layouts', 'Navigation', 'Styling'], duration: '8h 45m' },
        { section: 'State Management', lessons: ['setState', 'Provider', 'Riverpod', 'Bloc'], duration: '6h 30m' },
        { section: 'Backend & Firebase', lessons: ['Firebase Auth', 'Firestore', 'Cloud Functions', 'Storage'], duration: '9h 15m' },
        { section: 'Projects', lessons: ['E-commerce App', 'Social Media App', 'Weather App'], duration: '15h 0m' },
      ],
    },
    {
      id: 5,
      title: 'Digital Marketing & Growth Hacking Masterclass',
      slug: 'digital-marketing-masterclass',
      instructorId: 5,
      instructor: 'Lisa Wong',
      category: 'Digital Marketing',
      level: 'Beginner',
      rating: 4.8, reviews: 5680, students: 41200,
      price: 1490, originalPrice: 2990,
      duration: '28h 30m', lessons: 156, sections: 12,
      thumbnail: 'https://picsum.photos/seed/marketing5/640/360',
      isBestseller: true, isNew: false,
      tags: ['SEO', 'Google Ads', 'Facebook Ads', 'Content Marketing', 'Analytics'],
      language: 'ไทย',
      lastUpdated: 'ตุลาคม 2024',
      description: 'ครบทุก Digital Marketing channel ตั้งแต่ SEO, Google Ads ไปจนถึง Social Media Marketing',
      whatYouLearn: ['SEO ทั้ง On-page และ Off-page', 'Google Ads campaign management', 'Facebook & Instagram Ads', 'Content Marketing strategy', 'Email Marketing automation', 'Analytics และ Data-driven decisions'],
      curriculum: [
        { section: 'Marketing Fundamentals', lessons: ['Marketing Basics', 'Customer Journey', 'Brand Strategy'], duration: '2h 30m' },
        { section: 'SEO Mastery', lessons: ['Keyword Research', 'On-Page SEO', 'Link Building', 'Technical SEO'], duration: '6h 45m' },
        { section: 'Paid Advertising', lessons: ['Google Ads', 'Facebook Ads', 'Instagram Ads', 'Retargeting'], duration: '8h 20m' },
        { section: 'Content & Social', lessons: ['Content Strategy', 'Social Media', 'Video Marketing', 'Influencer'], duration: '5h 15m' },
        { section: 'Analytics & Growth', lessons: ['Google Analytics', 'Conversion Optimization', 'Growth Hacking'], duration: '5h 40m' },
      ],
    },
    {
      id: 6,
      title: 'Python for Everybody - Complete Beginner Course',
      slug: 'python-for-everybody',
      instructorId: 2,
      instructor: 'Mark Chen',
      category: 'Web Development',
      level: 'Beginner',
      rating: 4.7, reviews: 9200, students: 67000,
      price: 990, originalPrice: 1990,
      duration: '32h 10m', lessons: 184, sections: 11,
      thumbnail: 'https://picsum.photos/seed/python6/640/360',
      isBestseller: false, isNew: false,
      tags: ['Python', 'Programming', 'Automation', 'Web Scraping'],
      language: 'English',
      lastUpdated: 'สิงหาคม 2024',
      description: 'เรียน Python ตั้งแต่พื้นฐาน ไม่ต้องมีประสบการณ์ programming มาก่อน',
      whatYouLearn: ['Python syntax and basics', 'Data structures', 'File handling', 'Web scraping', 'API integration', 'Automation scripts'],
      curriculum: [
        { section: 'Getting Started', lessons: ['Installation', 'Your First Program', 'Variables'], duration: '2h 0m' },
        { section: 'Core Python', lessons: ['Control Flow', 'Functions', 'Lists', 'Dictionaries'], duration: '8h 30m' },
        { section: 'Advanced Topics', lessons: ['OOP', 'File I/O', 'Error Handling', 'Modules'], duration: '7h 20m' },
        { section: 'Real Projects', lessons: ['Calculator', 'Web Scraper', 'API Bot', 'Data Analyzer'], duration: '14h 20m' },
      ],
    },
    {
      id: 7,
      title: 'Business Analysis & Project Management',
      slug: 'business-analysis-pm',
      instructorId: 5,
      instructor: 'Lisa Wong',
      category: 'Business',
      level: 'Intermediate',
      rating: 4.6, reviews: 3410, students: 18700,
      price: 1690, originalPrice: 3290,
      duration: '24h 45m', lessons: 132, sections: 10,
      thumbnail: 'https://picsum.photos/seed/biz7/640/360',
      isBestseller: false, isNew: false,
      tags: ['Business Analysis', 'Project Management', 'Agile', 'Scrum', 'PMP'],
      language: 'English',
      lastUpdated: 'กรกฎาคม 2024',
      description: 'เรียนรู้ Business Analysis และ Project Management ด้วย Agile และ Scrum methodologies',
      whatYouLearn: ['Business requirements gathering', 'Process modeling', 'Agile & Scrum', 'Risk management', 'Stakeholder management'],
      curriculum: [
        { section: 'Business Analysis Fundamentals', lessons: ['BA Role', 'Requirements', 'Stakeholders'], duration: '4h 20m' },
        { section: 'Project Management', lessons: ['PMBOK', 'Planning', 'Execution', 'Monitoring'], duration: '6h 30m' },
        { section: 'Agile & Scrum', lessons: ['Agile Manifesto', 'Scrum Framework', 'Sprints', 'Retrospectives'], duration: '5h 45m' },
        { section: 'Tools & Techniques', lessons: ['Jira', 'Confluence', 'Visio', 'MS Project'], duration: '8h 10m' },
      ],
    },
    {
      id: 8,
      title: 'Photography Masterclass: From Beginner to Pro',
      slug: 'photography-masterclass',
      instructorId: 1,
      instructor: 'Sarah Johnson',
      category: 'Photography',
      level: 'Beginner',
      rating: 4.8, reviews: 7840, students: 34200,
      price: 1290, originalPrice: 2490,
      duration: '20h 35m', lessons: 112, sections: 9,
      thumbnail: 'https://picsum.photos/seed/photo8/640/360',
      isBestseller: false, isNew: true,
      tags: ['Photography', 'Lightroom', 'Photoshop', 'Composition', 'Lighting'],
      language: 'English',
      lastUpdated: 'ธันวาคม 2024',
      description: 'เรียนรู้การถ่ายภาพตั้งแต่พื้นฐานไปจนถึงการแก้ไขภาพระดับมืออาชีพด้วย Lightroom',
      whatYouLearn: ['Camera settings & exposure', 'Composition rules', 'Portrait photography', 'Landscape photography', 'Lightroom editing', 'Photoshop techniques'],
      curriculum: [
        { section: 'Camera Basics', lessons: ['Understanding Your Camera', 'Exposure Triangle', 'Focus & Depth of Field'], duration: '3h 20m' },
        { section: 'Composition', lessons: ['Rule of Thirds', 'Leading Lines', 'Framing', 'Color & Light'], duration: '4h 15m' },
        { section: 'Genres', lessons: ['Portrait', 'Landscape', 'Street', 'Product Photography'], duration: '6h 30m' },
        { section: 'Post-Processing', lessons: ['Lightroom Basics', 'Color Grading', 'Retouching', 'Exporting'], duration: '6h 30m' },
      ],
    },
    {
      id: 9,
      title: 'React Native: Build Mobile Apps with JavaScript',
      slug: 'react-native-mobile',
      instructorId: 1,
      instructor: 'Sarah Johnson',
      category: 'Mobile Apps',
      level: 'Intermediate',
      rating: 4.7, reviews: 3890, students: 21600,
      price: 1890, originalPrice: 3790,
      duration: '36h 20m', lessons: 198, sections: 13,
      thumbnail: 'https://picsum.photos/seed/reactnative9/640/360',
      isBestseller: false, isNew: false,
      tags: ['React Native', 'JavaScript', 'iOS', 'Android', 'Expo'],
      language: 'English',
      lastUpdated: 'ตุลาคม 2024',
      description: 'สร้าง mobile apps ด้วย React Native โดยใช้ความรู้ JavaScript ที่มีอยู่',
      whatYouLearn: ['React Native fundamentals', 'Navigation', 'State management with Redux', 'Native device APIs', 'Expo platform'],
      curriculum: [
        { section: 'Getting Started', lessons: ['Setup', 'First App', 'Core Components'], duration: '3h 40m' },
        { section: 'Core Concepts', lessons: ['Styling', 'Flexbox', 'Navigation', 'Gestures'], duration: '7h 20m' },
        { section: 'Data & State', lessons: ['Redux', 'Context API', 'AsyncStorage', 'API calls'], duration: '8h 15m' },
        { section: 'Device Features', lessons: ['Camera', 'Location', 'Push Notifications', 'Biometrics'], duration: '6h 30m' },
        { section: 'Full App Projects', lessons: ['Food Delivery', 'Fitness Tracker', 'Chat App'], duration: '10h 35m' },
      ],
    },
    {
      id: 10,
      title: 'Advanced Excel & Power BI for Business Analytics',
      slug: 'excel-power-bi-analytics',
      instructorId: 2,
      instructor: 'Mark Chen',
      category: 'Business',
      level: 'Beginner',
      rating: 4.6, reviews: 5120, students: 29800,
      price: 890, originalPrice: 1790,
      duration: '18h 40m', lessons: 98, sections: 8,
      thumbnail: 'https://picsum.photos/seed/excel10/640/360',
      isBestseller: false, isNew: false,
      tags: ['Excel', 'Power BI', 'Data Analysis', 'Business Intelligence'],
      language: 'ไทย/English',
      lastUpdated: 'กันยายน 2024',
      description: 'เรียนรู้ Excel และ Power BI สำหรับวิเคราะห์ข้อมูลทางธุรกิจ สร้าง Dashboard ที่สวยงามและมีประโยชน์',
      whatYouLearn: ['Advanced Excel formulas', 'Pivot Tables & Charts', 'Power Query', 'Power BI desktop', 'DAX formulas', 'Dashboard creation'],
      curriculum: [
        { section: 'Excel Mastery', lessons: ['Advanced Formulas', 'Pivot Tables', 'VLOOKUP & XLOOKUP', 'Macros'], duration: '6h 20m' },
        { section: 'Power Query', lessons: ['Data Import', 'Transformations', 'Merging Data'], duration: '3h 30m' },
        { section: 'Power BI', lessons: ['Interface', 'Data Modeling', 'Visualizations', 'DAX'], duration: '5h 40m' },
        { section: 'Dashboard Projects', lessons: ['Sales Dashboard', 'HR Analytics', 'Finance Report'], duration: '3h 10m' },
      ],
    },
    {
      id: 11,
      title: 'TypeScript: The Complete Developer Guide',
      slug: 'typescript-complete-guide',
      instructorId: 1,
      instructor: 'Sarah Johnson',
      category: 'Web Development',
      level: 'Intermediate',
      rating: 4.8, reviews: 4560, students: 26300,
      price: 1590, originalPrice: 3190,
      duration: '27h 45m', lessons: 155, sections: 11,
      thumbnail: 'https://picsum.photos/seed/typescript11/640/360',
      isBestseller: false, isNew: true,
      tags: ['TypeScript', 'JavaScript', 'Node.js', 'Angular', 'React'],
      language: 'English',
      lastUpdated: 'พฤศจิกายน 2024',
      description: 'เรียนรู้ TypeScript ตั้งแต่พื้นฐานไปจนถึง advanced patterns สำหรับ professional development',
      whatYouLearn: ['TypeScript type system', 'Interfaces & generics', 'Decorators', 'TypeScript with React', 'TypeScript with Node.js'],
      curriculum: [
        { section: 'TypeScript Basics', lessons: ['Types', 'Interfaces', 'Classes', 'Functions'], duration: '6h 20m' },
        { section: 'Advanced Types', lessons: ['Generics', 'Utility Types', 'Conditional Types', 'Mapped Types'], duration: '7h 30m' },
        { section: 'TypeScript in Practice', lessons: ['React + TS', 'Node.js + TS', 'Testing with TS'], duration: '8h 45m' },
        { section: 'Projects', lessons: ['REST API', 'React App', 'CLI Tool'], duration: '5h 10m' },
      ],
    },
    {
      id: 12,
      title: 'AWS Cloud Practitioner & Solutions Architect',
      slug: 'aws-cloud-certification',
      instructorId: 2,
      instructor: 'Mark Chen',
      category: 'Web Development',
      level: 'Intermediate',
      rating: 4.9, reviews: 6780, students: 44100,
      price: 2790, originalPrice: 5490,
      duration: '58h 10m', lessons: 312, sections: 20,
      thumbnail: 'https://picsum.photos/seed/aws12/640/360',
      isBestseller: true, isNew: false,
      tags: ['AWS', 'Cloud', 'DevOps', 'Docker', 'Kubernetes'],
      language: 'English',
      lastUpdated: 'ตุลาคม 2024',
      description: 'เตรียมสอบ AWS Certified Solutions Architect พร้อม hands-on labs ครบถ้วน',
      whatYouLearn: ['AWS core services', 'EC2, S3, RDS, Lambda', 'VPC & networking', 'Security & IAM', 'High availability architectures', 'Cost optimization'],
      curriculum: [
        { section: 'AWS Fundamentals', lessons: ['Cloud Concepts', 'AWS Global Infrastructure', 'IAM'], duration: '6h 30m' },
        { section: 'Compute & Storage', lessons: ['EC2', 'Lambda', 'S3', 'EBS', 'EFS'], duration: '12h 20m' },
        { section: 'Networking & Security', lessons: ['VPC', 'Route 53', 'CloudFront', 'WAF', 'Shield'], duration: '9h 45m' },
        { section: 'Databases & Analytics', lessons: ['RDS', 'DynamoDB', 'ElastiCache', 'Redshift'], duration: '8h 30m' },
        { section: 'Practice Exams', lessons: ['Exam 1', 'Exam 2', 'Exam 3', 'Review Sessions'], duration: '21h 5m' },
      ],
    },
  ],

  /* ─── REVIEWS ─── */
  reviews: [
    { id: 1, user: 'กมลชนก ส.', avatar: 'https://ui-avatars.com/api/?name=Kamonchanok&background=C3BEF7&color=595758&size=64', rating: 5, date: '3 สัปดาห์ที่แล้ว', comment: 'หลักสูตรนี้ดีมากๆ เนื้อหาครบ อธิบายเข้าใจง่าย อาจารย์ตอบคำถามในบอร์ดเร็วมาก ได้งานใหม่หลังจากเรียนจบเพียง 2 เดือนเลยครับ! แนะนำมากๆ สำหรับคนที่อยากเปลี่ยนสายมาทำ dev' },
    { id: 2, user: 'วรวิทย์ พ.', avatar: 'https://ui-avatars.com/api/?name=Worawit&background=D6F6DD&color=595758&size=64', rating: 5, date: '1 เดือนที่แล้ว', comment: 'เนื้อหาอัปเดตตลอด ไม่เหมือนหลักสูตรอื่นที่เนื้อหาเก่า คุณภาพวิดีโอดี เสียงชัด โปรเจกต์ที่ทำได้นำไปใช้งานจริงได้เลย 5 ดาวเต็มๆ' },
    { id: 3, user: 'ปริยากร ม.', avatar: 'https://ui-avatars.com/api/?name=Pariyakorn&background=EBD2B4&color=595758&size=64', rating: 4, date: '2 เดือนที่แล้ว', comment: 'ดีมากค่ะ แต่บางส่วนเร็วไปนิด ต้องหยุดดูหลายรอบ รวมๆ แล้วคุ้มค่ามาก ได้ความรู้เยอะมาก' },
    { id: 4, user: 'ธนภัทร ว.', avatar: 'https://ui-avatars.com/api/?name=Thanapat&background=CA895F&color=fff&size=64', rating: 5, date: '2 เดือนที่แล้ว', comment: 'Best investment I have ever made! เรียนมา 6 เดือน ได้งาน Junior Dev แล้ว เงินเดือนเพิ่มขึ้น 80%' },
    { id: 5, user: 'ศิริวรรณ ก.', avatar: 'https://ui-avatars.com/api/?name=Siriwan&background=A49BF0&color=fff&size=64', rating: 5, date: '3 เดือนที่แล้ว', comment: 'หลักสูตรเดียวที่อธิบาย React hooks ได้ชัดเจนที่สุดที่เคยเรียนมาค่ะ instructor เก่งมาก' },
  ],

  /* ─── STUDENT DASHBOARD DATA ─── */
  studentDashboard: {
    user: {
      name: 'สมศักดิ์ รักเรียน',
      firstName: 'สมศักดิ์',
      email: 'somsak@example.com',
      avatar: 'https://ui-avatars.com/api/?name=Somsak+Rak&background=CA895F&color=fff&size=128',
      joinDate: 'มกราคม 2024',
      title: 'Web Developer (Learning)',
    },
    stats: [
      { label: 'คอร์สที่ลงทะเบียน', value: '12', change: '+2', trend: 'up', icon: '📚', color: '#CA895F', bg: '#FBF3EC' },
      { label: 'คอร์สที่เรียนจบ', value: '7', change: '+1', trend: 'up', icon: '✅', color: '#22C55E', bg: '#F0FDF4' },
      { label: 'ชั่วโมงที่เรียน', value: '248h', change: '+12h', trend: 'up', icon: '⏱️', color: '#3B82F6', bg: '#EFF6FF' },
      { label: 'ใบประกาศนียบัตร', value: '5', change: '+1', trend: 'up', icon: '🏆', color: '#A49BF0', bg: '#F5F3FE' },
    ],
    inProgressCourses: [
      { id: 1, title: 'Complete Web Development Bootcamp 2024', instructor: 'Sarah Johnson', progress: 68, thumbnail: 'https://picsum.photos/seed/web1/320/180', lastLesson: 'React Hooks Deep Dive', nextLesson: 'Custom Hooks', timeLeft: '16h 45m left' },
      { id: 2, title: 'Data Science & Machine Learning Masterclass', instructor: 'Mark Chen', progress: 34, thumbnail: 'https://picsum.photos/seed/data2/320/180', lastLesson: 'Linear Regression', nextLesson: 'Logistic Regression', timeLeft: '42h 30m left' },
      { id: 3, title: 'UI/UX Design Professional Certificate', instructor: 'Priya Patel', progress: 91, thumbnail: 'https://picsum.photos/seed/design3/320/180', lastLesson: 'Portfolio Project', nextLesson: 'Final Review', timeLeft: '3h 20m left' },
    ],
    recentActivity: [
      { type: 'lesson', text: 'เรียนจบ: React Router v6', time: '2 ชั่วโมงที่แล้ว', icon: '▶️' },
      { type: 'quiz', text: 'ทำแบบทดสอบได้ 92%: JavaScript Async', time: 'เมื่อวาน', icon: '📝' },
      { type: 'cert', text: 'ได้รับ Certificate: Python Fundamentals', time: '3 วันที่แล้ว', icon: '🏆' },
      { type: 'lesson', text: 'เรียนจบ: CSS Grid Layout', time: '4 วันที่แล้ว', icon: '▶️' },
      { type: 'enroll', text: 'ลงทะเบียนเรียน: TypeScript Complete Guide', time: '1 สัปดาห์ที่แล้ว', icon: '📚' },
    ],
  },

  /* ─── INSTRUCTOR DASHBOARD DATA ─── */
  instructorDashboard: {
    user: { name: 'Sarah Johnson', avatar: 'https://ui-avatars.com/api/?name=Sarah+Johnson&background=CA895F&color=fff&size=128', title: 'Senior Full-Stack Developer' },
    stats: [
      { label: 'รายได้เดือนนี้', value: '฿84,200', change: '+18%', trend: 'up', icon: '💰', color: '#22C55E', bg: '#F0FDF4' },
      { label: 'นักเรียนทั้งหมด', value: '45,287', change: '+3.2%', trend: 'up', icon: '👥', color: '#CA895F', bg: '#FBF3EC' },
      { label: 'คอร์สที่สอน', value: '8', change: '+1', trend: 'up', icon: '📚', color: '#3B82F6', bg: '#EFF6FF' },
      { label: 'คะแนนเฉลี่ย', value: '4.9', change: '+0.1', trend: 'up', icon: '⭐', color: '#F59E0B', bg: '#FFFBEB' },
    ],
    courses: [
      { id: 1, title: 'Complete Web Development Bootcamp 2024', students: 89000, rating: 4.8, revenue: '฿1,782,000', status: 'published' },
      { id: 11, title: 'TypeScript: The Complete Developer Guide', students: 26300, rating: 4.8, revenue: '฿418,170', status: 'published' },
      { id: 9, title: 'React Native: Build Mobile Apps', students: 21600, rating: 4.7, revenue: '฿408,240', status: 'published' },
      { id: 8, title: 'Photography Masterclass', students: 34200, rating: 4.8, revenue: '฿441,180', status: 'published' },
    ],
    monthlyRevenue: [42000, 51000, 38000, 67000, 72000, 84200],
    monthLabels: ['ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],
  },

  /* ─── ADMIN DASHBOARD DATA ─── */
  adminDashboard: {
    stats: [
      { label: 'ผู้ใช้ทั้งหมด', value: '124,589', change: '+12%', trend: 'up', icon: '👥', color: '#3B82F6', bg: '#EFF6FF' },
      { label: 'คอร์สทั้งหมด', value: '5,247', change: '+8%', trend: 'up', icon: '📚', color: '#CA895F', bg: '#FBF3EC' },
      { label: 'รายได้รวม (เดือนนี้)', value: '฿2.4M', change: '+22%', trend: 'up', icon: '💰', color: '#22C55E', bg: '#F0FDF4' },
      { label: 'Active Sessions', value: '3,841', change: '-5%', trend: 'down', icon: '🟢', color: '#A49BF0', bg: '#F5F3FE' },
    ],
    recentUsers: [
      { name: 'กมลชนก สุริยา', email: 'kamonchanok@email.com', role: 'Student', joined: '25 ธ.ค. 2024', status: 'active', avatar: 'https://ui-avatars.com/api/?name=K+S&background=C3BEF7&color=595758' },
      { name: 'วรวิทย์ พานทอง', email: 'worawit@email.com', role: 'Instructor', joined: '24 ธ.ค. 2024', status: 'active', avatar: 'https://ui-avatars.com/api/?name=W+P&background=D6F6DD&color=595758' },
      { name: 'ปริยากร มณีรัตน์', email: 'pariya@email.com', role: 'Student', joined: '23 ธ.ค. 2024', status: 'active', avatar: 'https://ui-avatars.com/api/?name=P+M&background=EBD2B4&color=595758' },
      { name: 'ธนภัทร วงศ์สุวรรณ', email: 'thanapat@email.com', role: 'Student', joined: '22 ธ.ค. 2024', status: 'inactive', avatar: 'https://ui-avatars.com/api/?name=T+W&background=CA895F&color=fff' },
      { name: 'ศิริวรรณ กาญจนา', email: 'siriwan@email.com', role: 'Instructor', joined: '20 ธ.ค. 2024', status: 'active', avatar: 'https://ui-avatars.com/api/?name=S+K&background=A49BF0&color=fff' },
    ],
    recentTransactions: [
      { id: 'TXN-001', user: 'กมลชนก ส.', course: 'Complete Web Dev Bootcamp', amount: '฿1,990', date: '25 ธ.ค. 2024', status: 'paid' },
      { id: 'TXN-002', user: 'ธนภัทร ว.', course: 'Data Science Masterclass', amount: '฿2,490', date: '24 ธ.ค. 2024', status: 'paid' },
      { id: 'TXN-003', user: 'วรวิทย์ พ.', course: 'UI/UX Design Pro', amount: '฿1,790', date: '23 ธ.ค. 2024', status: 'pending' },
      { id: 'TXN-004', user: 'ปริยากร ม.', course: 'Flutter Development', amount: '฿2,190', date: '22 ธ.ค. 2024', status: 'paid' },
      { id: 'TXN-005', user: 'สมศักดิ์ ร.', course: 'AWS Cloud Architect', amount: '฿2,790', date: '21 ธ.ค. 2024', status: 'failed' },
    ],
  },

  /* ─── MY COURSES (Student enrolled courses) ─── */
  myCourses: [
    { id: 1, title: 'Complete Web Development Bootcamp 2024', instructor: 'Sarah Johnson', thumbnail: 'https://picsum.photos/seed/web1/320/180', progress: 68, status: 'in-progress', enrolledDate: '1 ต.ค. 2024', lastAccessed: '2 ชั่วโมงที่แล้ว', category: 'Web Development' },
    { id: 2, title: 'Data Science & Machine Learning Masterclass', instructor: 'Mark Chen', thumbnail: 'https://picsum.photos/seed/data2/320/180', progress: 34, status: 'in-progress', enrolledDate: '15 ต.ค. 2024', lastAccessed: '1 วันที่แล้ว', category: 'Data Science' },
    { id: 3, title: 'UI/UX Design Professional Certificate', instructor: 'Priya Patel', thumbnail: 'https://picsum.photos/seed/design3/320/180', progress: 91, status: 'in-progress', enrolledDate: '5 ก.ย. 2024', lastAccessed: '3 วันที่แล้ว', category: 'UI/UX Design' },
    { id: 5, title: 'Digital Marketing Masterclass', instructor: 'Lisa Wong', thumbnail: 'https://picsum.photos/seed/marketing5/320/180', progress: 100, status: 'completed', enrolledDate: '1 ส.ค. 2024', lastAccessed: '2 เดือนที่แล้ว', category: 'Digital Marketing' },
    { id: 6, title: 'Python for Everybody', instructor: 'Mark Chen', thumbnail: 'https://picsum.photos/seed/python6/320/180', progress: 100, status: 'completed', enrolledDate: '15 มิ.ย. 2024', lastAccessed: '3 เดือนที่แล้ว', category: 'Programming' },
    { id: 10, title: 'Advanced Excel & Power BI', instructor: 'Mark Chen', thumbnail: 'https://picsum.photos/seed/excel10/320/180', progress: 100, status: 'completed', enrolledDate: '1 พ.ค. 2024', lastAccessed: '4 เดือนที่แล้ว', category: 'Business' },
    { id: 8, title: 'Photography Masterclass', instructor: 'Sarah Johnson', thumbnail: 'https://picsum.photos/seed/photo8/320/180', progress: 0, status: 'not-started', enrolledDate: '20 ธ.ค. 2024', lastAccessed: 'ยังไม่เริ่ม', category: 'Photography' },
  ],

  /* ─── CHECKOUT DATA ─── */
  checkout: {
    course: { title: 'Complete Web Development Bootcamp 2024', instructor: 'Sarah Johnson', thumbnail: 'https://picsum.photos/seed/web1/200/120', price: 1990, originalPrice: 3990, rating: 4.8, reviews: 12430 },
    paymentMethods: ['credit-card', 'promptpay', 'truemoney', 'bank-transfer'],
  },
};

/* Helper Functions */
function getCourse(id) { return MOCK.courses.find(c => c.id === parseInt(id)); }
function getInstructor(id) { return MOCK.instructors.find(i => i.id === parseInt(id)); }
function getCoursesByCategory(cat) { return MOCK.courses.filter(c => c.category === cat); }
function getBestsellers() { return MOCK.courses.filter(c => c.isBestseller); }
function formatPrice(price) { return `฿${price.toLocaleString()}`; }
function renderStars(rating) {
  const full = Math.floor(rating), half = rating % 1 >= 0.5;
  let stars = '';
  for (let i = 0; i < full; i++) stars += '<span class="star filled">★</span>';
  if (half) stars += '<span class="star half">★</span>';
  for (let i = full + (half ? 1 : 0); i < 5; i++) stars += '<span class="star">★</span>';
  return `<span class="stars">${stars}</span>`;
}
